name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v4

      # Archive the content of the repository
      - name: Archive repository on push
        run: |
          mkdir -p archive
          TIMESTAMP=$(date +'%Y-%m-%d_%H-%M-%S')
          zip -r "archive/repository_$TIMESTAMP.zip" .
          echo "Repository archived as archive/repository_$TIMESTAMP.zip"

      # Upload the archive as an artifact
      - name: Upload Archive
        uses: actions/upload-artifact@v3
        with:
          name: repository-archive
          path: archive/
